Make uuid available
SatelliteQE/manifester pull request #33
Opened 2024-03-18 07:33 UTC by dosas

As described here https://github.com/SatelliteQE/robottelo/pull/14405#discussion_r1526828098 this will make the uuid available

2024-03-19 10:49 UTC, dosas commented
@synkd do you have any idea why this test is failing?
```
_____________________ test_delete_subscription_allocation ______________________

    def test_delete_subscription_allocation():
        """Test that manifester's delete_subscription_allocation method deletes a subscription allocation."""
        manifester = Manifester(manifest_category=MANIFEST_DATA, requester=RhsmApiStub(in_dict=None))
        manifester.get_manifest()
>       response = manifester.delete_subscription_allocation()

tests/test_manifester.py:251: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/manifester/manifester.py:194: in delete_subscription_allocation
    response = simple_retry(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cmd = <bound method RhsmApiStub.delete of {}>
cmd_args = ['[https://api.access.redhat.com/management/v1/allocations/{}](https://api.access.redhat.com/management/v1/allocations/%7B%7D)']
cmd_kwargs = {'headers': {'Authorization': '*** is a simulated access token'}, 'params': {'force': 'true'}, 'proxies': <Box: {'https': ''}>}
max_timeout = 240, _cur_timeout = 1

    def simple_retry(cmd, cmd_args=None, cmd_kwargs=None, max_timeout=240, _cur_timeout=1):
        """Re(Try) a function given its args and kwargs up until a max timeout."""
        cmd_args = cmd_args if cmd_args else []
        cmd_kwargs = cmd_kwargs if cmd_kwargs else {}
        # If additional debug information is needed, the following log entry can be modified to
        # include the data being passed by adding {cmd_kwargs=} to the f-string. Please do so
        # with caution as some data (notably the offline token) should be treated as a secret.
        logger.debug(f"Sending request to endpoint {cmd_args}")
        response = cmd(*cmd_args, **cmd_kwargs)
>       logger.debug(f"Response status code is {response.status_code}")
E       AttributeError: 'NoneType' object has no attribute 'status_code'

/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/manifester/helpers.py:25: AttributeError
```

2024-03-19 16:07 UTC, synkd requested changes
Thank you for the PR. I'm requesting a change based on a quirk of how Manifester's unit tests are implemented. This change should both pass the unit tests and function in normal use (whereas `self.allocation_uuid.uuid` will throw an `AttributeError` outside of the unit tests).

2024-03-20 07:56 UTC, dosas commented on manifester/manifester.py
> +        manifest.uuid = self.allocation_uuid.uuid
Good to know :)

2024-03-20 14:29 UTC, synkd approved these changes

2024-03-20 14:29 UTC, merged