Add `scripts` section to pyproject.toml
SatelliteQE/manifester pull request #39
Opened 2024-06-04 15:34 UTC by synkd

When I converted Manifester to pyproject.toml, I did not include a `project.scripts` section. As a result, an executable for the Manifester CLI is not installed when the Manifester package is installed. This PR adds a `project.scripts` section to pyproject.toml so the Manifester CLI is easily accessible.

2024-06-04 21:02 UTC, JacobCallahan requested changes
Can you also add a call to manifester --help in the GitHub action post-install?

2024-06-05 12:58 UTC, ogajduse approved these changes
ACK, pending Jake's comment.

2024-06-05 17:50 UTC, synkd commented
@JacobCallahan just to clarify, do you mean in the Unit Tests section of `workflows/codeql-analysis.yml`?

2024-06-06 20:11 UTC, synkd commented
@JacobCallahan I'm not totally certain which installation you're referring to, but Manifester gets installed in the Unit Tests section of the codeql-analysis GitHub Action and in the Setup and Build section of the python-publish GitHub Action. I've added a call to `manifester --help` to the former and can add it to the latter as well if you would like.

2024-06-06 21:19 UTC, JacobCallahan approved these changes
That's perfect. Just to validate that the basic cli works

2024-06-07 20:13 UTC, merged