Modify Manifester class to work with MockStub
SatelliteQE/manifester pull request #4
Opened 2022-06-01 21:26 UTC by synkd

Add a class to test_manifester.py to enable requests to be sent to a
MockStub version of the requests package instead of sending live
requests to the API. Modify the Manifester class to use the
MockStub-based requests when running unit tests. Add a helper function
to generate mock HTTP response codes.

This PR should start as a draft, as there is currently an issue with
integrating simple_retry with the RhsmApiStub class:

http://pastebin.test.redhat.com/1055597

2023-12-01 16:51 UTC, JacobCallahan requested changes
ACK on most everything. Just one request for your Ruff rules. This will require you to re-run ruff against the project.

2023-12-04 16:57 UTC, synkd commented on pyproject.toml
> +]
This is now done. Ruff found 100 errors when using the pyproject.toml based on Broker's, so my last commit also introduces numerous small changes to get the whole project into a passing state.

2023-12-04 19:45 UTC, JacobCallahan requested changes
Couple of small things

2023-12-04 19:45 UTC, JacobCallahan commented on pyproject.toml
> +    "Programming Language :: Python :: 3.11",
Since you have it in your checks, you can ad py 3.12 to this list.

2023-12-04 19:45 UTC, JacobCallahan commented on tests/test_manifester.py
> +    "proxies": {"https:"},
is this meant to be a set or a dictionary?

2023-12-05 19:41 UTC, synkd commented
Looking at the CodeQL failures, the checkout action is merging in commit 79a4b4e [1], although the most recent commit in this PR is 2af7760. I'm trying to determine why this is happening, and I'm open to suggestions if anyone has see something like this before.

[1] https://github.com/SatelliteQE/manifester/actions/runs/7091796806/job/19342080413#step:2:77

2023-12-05 20:29 UTC, JacobCallahan commented
Strange, I've not seeing that before. Are the tests passing locally?
Perhaps doing an interactive rebase and squashing some commits might help. shot in the dark..

2023-12-07 20:47 UTC, Griffin-Sullivan approved these changes
Haven't gotten to tests yet. Mostly just being picky about constants. There's a couple other places you used these. Definitely non-blocking just stylistic.

2023-12-07 21:46 UTC, JacobCallahan commented on manifester/helpers.py
> +    expected_length = 8
since these are local, it's less important to stress constant values with capitalization.

2023-12-12 19:50 UTC, synkd commented on .github/workflows/codeql-analysis.yml
> +      uses: github/codeql-action/init@v2
Ack, I will look into that, but I don't plan to implement it in this PR.

2023-12-12 20:02 UTC, synkd commented
I'm not sure if I have fully resolved the flakiness issue, but I just had three successful local runs of all the tests, so I'm moving on for now. Here's one, just for the record:
```
$ pytest tests/test_manifester.py
============================================================================================================================= test session starts =============================================================================================================================
platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/dsynk/manifester
configfile: pyproject.toml
collected 10 items                                                                                                                                                                                                                                                            

tests/test_manifester.py ..........                                                                                                                                                                                                                                     [100%]

======================================================================================================================= 10 passed in 132.35s (0:02:12) ========================================================================================================================
```
I was able to reproduce the CI failure by renaming my local `manifester_settings.yaml`, so something about processing the manifest data as a dict is not functioning properly. I'll work on debugging that next.

2023-12-12 21:14 UTC, synkd commented
Ok, the issue with tests failing was due to some `get()` calls defaulting to pulling values from settings in a few places. I'm actually having trouble understanding why exactly this is happening. My best guess is that the way that Robottelo initializes settings causes the `settings` object to have a `URL` attribute and that this is not the case for the way that Manifester initializes settings. With the `get()` defaults removed, the tests pass, and Robottelo tests that use Manifester are still passing as well. I don't think this change will affect any current implementations of Manifester, but I'm open to arguments on whether I should find a different workaround.

To address the test flakiness issue, I've also changed the default `fail_rate` for HTTP response codes to 0 for most tests. I'm open to arguments on this point as well, but I don't think there is a major advantage to randomly exercising `simple_retry`. I would be willing to write a separate test with a less deterministic fail rate and dig into this issue further, but I would prefer to do that in a separate PR at this point.

2023-12-14 21:21 UTC, JacobCallahan approved these changes

2023-12-15 21:44 UTC, merged